package interfaceusuario;

import acesso.GerenciadorTransacoes;
import javax.swing.AbstractListModel;

public class JanelaCRUD extends javax.swing.JFrame {
    private final GerenciadorTransacoes gerTrans;
    private AbstractListModel listaUsuarios;
    private AbstractListModel listaLivros;
    private AbstractListModel listaPedidos;
    
    public JanelaCRUD(GerenciadorTransacoes gerTrans) {
        this.gerTrans = gerTrans;
        
        listaUsuarios = new AbstractListModel(){
            @Override
            public int getSize() {return gerTrans.getListaUsuarios().size();}
            @Override
            public Object getElementAt(int index) {return gerTrans.getListaUsuarios().get(index);}
        };
        
        listaLivros = new AbstractListModel(){
            @Override
            public int getSize() {return gerTrans.getListaLivros().size();}
            @Override
            public Object getElementAt(int index) {return gerTrans.getListaLivros().get(index);}
        };
        
        listaPedidos = new AbstractListModel(){
            @Override
            public int getSize() {return gerTrans.getListaPedidos().size();}
            @Override
            public Object getElementAt(int index) {return gerTrans.getListaPedidos().get(index);}
        };
    
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BD01CRUDPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("BD01CRUDPU").createEntityManager();
        usuariosQuery = java.beans.Beans.isDesignTime() ? null : BD01CRUDPUEntityManager.createQuery("SELECT u FROM Usuarios u");
        usuariosList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usuariosQuery.getResultList();
        jScrollPane_lista = new javax.swing.JScrollPane();
        jList_lista = new javax.swing.JList();
        jButton_adicionar = new javax.swing.JButton();
        jButton_visualizar = new javax.swing.JButton();
        jButton_excluir = new javax.swing.JButton();
        jComboBox_tabelas = new javax.swing.JComboBox();
        jMenuBar_menu = new javax.swing.JMenuBar();
        jMenu_arquivo = new javax.swing.JMenu();
        jMenu_editar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList_lista.setModel(listaUsuarios);
        jScrollPane_lista.setViewportView(jList_lista);

        jButton_adicionar.setText("Adicionar");

        jButton_visualizar.setText("Visualizar");

        jButton_excluir.setText("Excluir");

        jComboBox_tabelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuários", "Livros", "Pedidos" }));
        jComboBox_tabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tabelasActionPerformed(evt);
            }
        });

        jMenu_arquivo.setText("Arquivo");
        jMenuBar_menu.add(jMenu_arquivo);

        jMenu_editar.setText("Editar");
        jMenuBar_menu.add(jMenu_editar);

        setJMenuBar(jMenuBar_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_lista)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_tabelas, 0, 145, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_visualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_excluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_adicionar)
                    .addComponent(jButton_visualizar)
                    .addComponent(jButton_excluir)
                    .addComponent(jComboBox_tabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_lista, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_tabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tabelasActionPerformed
        switch(jComboBox_tabelas.getSelectedIndex()){
            case 0:
                jList_lista.setModel(listaUsuarios); 
            break;
            case 1:
                jList_lista.setModel(listaLivros);
            break;
            case 2:
                jList_lista.setModel(listaPedidos);
            break;
            default:
                System.out.println("ERROR: ComboBox out of range");
            break;
        }
    }//GEN-LAST:event_jComboBox_tabelasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager BD01CRUDPUEntityManager;
    private javax.swing.JButton jButton_adicionar;
    private javax.swing.JButton jButton_excluir;
    private javax.swing.JButton jButton_visualizar;
    private javax.swing.JComboBox jComboBox_tabelas;
    private javax.swing.JList jList_lista;
    private javax.swing.JMenuBar jMenuBar_menu;
    private javax.swing.JMenu jMenu_arquivo;
    private javax.swing.JMenu jMenu_editar;
    private javax.swing.JScrollPane jScrollPane_lista;
    private java.util.List<entidades.Usuarios> usuariosList;
    private javax.persistence.Query usuariosQuery;
    // End of variables declaration//GEN-END:variables
}
